version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            pwd
            ls -all
            aws cloudformation deploy \
              --template-file file://~/project/template.yml \
              --stack-name my-stack --region ap-south-1
workflows:
  my_workflow:
    jobs:
      - create_infrastructure
